on: push
name: deploy
jobs:
   deploy:
      name: deploy to cluster
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
           username: ${{  secrets.DOCKER_USERNAME  }}
           password: ${{  secrets.DOCKER_PASSWORD  }}
           repository: ${{ github.repository }}
           tag_with_ref: true
           tag_with_sha: true
           tags: ${{ github.sha }}
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
           config: ${{ secrets.KUBE_CONFIG_DATA }}
           command: set image --record deployment/myapp container=${{ github.repository }}:${{ github.sha }}
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
           config: ${{ secrets.KUBE_CONFIG_DATA }}
           version: v1.21.0 # specify kubectl binary version explicitly
           command: rollout status deployment/my-app
